# -*- coding: utf-8 -*-
"""pillow-image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tgJLQrvJ2Tm1RCy865nuCIxGcnZkrLH9
"""

from PIL import Image

img = Image.open("red-roses.jpg")
img

# split RGB and show different color
r,g,b = img.split()
r

g

b

swapped = Image.merge("RGB", (g,b,r))
swapped